version: '3.7'

services:
  goteth:
    build:
      context: ./
      dockerfile: Dockerfile
    init: true
    command: >-
      blocks
      --log-level=${ANALYZER_LOG_LEVEL}
      --bn-endpoint=${ANALYZER_BN_ENDPOINT}
      --el-endpoint=${ANALYZER_EL_ENDPOINT:-}
      --init-slot=${ANALYZER_INIT_SLOT}
      --final-slot=${ANALYZER_FINAL_SLOT}
      --db-url=${ANALYZER_DB_URL}
      --workers-num=${ANALYZER_WORKERS_NUM}
      --db-workers-num=${ANALYZER_DB_WORKERS_NUM}
      --download-mode=${ANALYZER_DOWNLOAD_MODE}
      --metrics=${ANALYZER_METRICS}
      --prometheus-port=${ANALYZER_PROMETHEUS_PORT:-9081}
    network_mode: 'host'
                
  clickhouse:
    image: clickhouse/clickhouse-server
    user: "$UID:$GID"
    container_name: clickhouse
    hostname: clickhouse
    environment:
      - CLICKHOUSE_DB=${CH_DB:-my_database}
      - CLICKHOUSE_USER=${CH_USER:-username}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=${CH_PASSWORD:-password}
    volumes:
      - ./clickhouse_data/data:/var/lib/clickhouse/
      - ./clickhouse_data/logs:/var/log/clickhouse-server/
    ports:
      - "127.0.0.1:${CH_HTTP_PORT:-8123}:8123"
      - "127.0.0.1:${CH_NATIVE_PORT:-9000}:9000"